# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto.admin.v1 import powergate_admin_pb2 as proto_dot_admin_dot_v1_dot_powergate__admin__pb2


class PowergateAdminServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NewAddress = channel.unary_unary(
                '/proto.admin.v1.PowergateAdminService/NewAddress',
                request_serializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.NewAddressRequest.SerializeToString,
                response_deserializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.NewAddressResponse.FromString,
                )
        self.Addresses = channel.unary_unary(
                '/proto.admin.v1.PowergateAdminService/Addresses',
                request_serializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.AddressesRequest.SerializeToString,
                response_deserializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.AddressesResponse.FromString,
                )
        self.SendFil = channel.unary_unary(
                '/proto.admin.v1.PowergateAdminService/SendFil',
                request_serializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.SendFilRequest.SerializeToString,
                response_deserializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.SendFilResponse.FromString,
                )
        self.CreateStorageProfile = channel.unary_unary(
                '/proto.admin.v1.PowergateAdminService/CreateStorageProfile',
                request_serializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.CreateStorageProfileRequest.SerializeToString,
                response_deserializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.CreateStorageProfileResponse.FromString,
                )
        self.StorageProfiles = channel.unary_unary(
                '/proto.admin.v1.PowergateAdminService/StorageProfiles',
                request_serializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.StorageProfilesRequest.SerializeToString,
                response_deserializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.StorageProfilesResponse.FromString,
                )
        self.QueuedStorageJobs = channel.unary_unary(
                '/proto.admin.v1.PowergateAdminService/QueuedStorageJobs',
                request_serializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.QueuedStorageJobsRequest.SerializeToString,
                response_deserializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.QueuedStorageJobsResponse.FromString,
                )
        self.ExecutingStorageJobs = channel.unary_unary(
                '/proto.admin.v1.PowergateAdminService/ExecutingStorageJobs',
                request_serializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.ExecutingStorageJobsRequest.SerializeToString,
                response_deserializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.ExecutingStorageJobsResponse.FromString,
                )
        self.LatestFinalStorageJobs = channel.unary_unary(
                '/proto.admin.v1.PowergateAdminService/LatestFinalStorageJobs',
                request_serializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.LatestFinalStorageJobsRequest.SerializeToString,
                response_deserializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.LatestFinalStorageJobsResponse.FromString,
                )
        self.LatestSuccessfulStorageJobs = channel.unary_unary(
                '/proto.admin.v1.PowergateAdminService/LatestSuccessfulStorageJobs',
                request_serializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.LatestSuccessfulStorageJobsRequest.SerializeToString,
                response_deserializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.LatestSuccessfulStorageJobsResponse.FromString,
                )
        self.StorageJobsSummary = channel.unary_unary(
                '/proto.admin.v1.PowergateAdminService/StorageJobsSummary',
                request_serializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.StorageJobsSummaryRequest.SerializeToString,
                response_deserializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.StorageJobsSummaryResponse.FromString,
                )


class PowergateAdminServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def NewAddress(self, request, context):
        """Wallet
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Addresses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendFil(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateStorageProfile(self, request, context):
        """Profiles
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StorageProfiles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueuedStorageJobs(self, request, context):
        """Jobs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecutingStorageJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LatestFinalStorageJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LatestSuccessfulStorageJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StorageJobsSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PowergateAdminServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NewAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.NewAddress,
                    request_deserializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.NewAddressRequest.FromString,
                    response_serializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.NewAddressResponse.SerializeToString,
            ),
            'Addresses': grpc.unary_unary_rpc_method_handler(
                    servicer.Addresses,
                    request_deserializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.AddressesRequest.FromString,
                    response_serializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.AddressesResponse.SerializeToString,
            ),
            'SendFil': grpc.unary_unary_rpc_method_handler(
                    servicer.SendFil,
                    request_deserializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.SendFilRequest.FromString,
                    response_serializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.SendFilResponse.SerializeToString,
            ),
            'CreateStorageProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateStorageProfile,
                    request_deserializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.CreateStorageProfileRequest.FromString,
                    response_serializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.CreateStorageProfileResponse.SerializeToString,
            ),
            'StorageProfiles': grpc.unary_unary_rpc_method_handler(
                    servicer.StorageProfiles,
                    request_deserializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.StorageProfilesRequest.FromString,
                    response_serializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.StorageProfilesResponse.SerializeToString,
            ),
            'QueuedStorageJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.QueuedStorageJobs,
                    request_deserializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.QueuedStorageJobsRequest.FromString,
                    response_serializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.QueuedStorageJobsResponse.SerializeToString,
            ),
            'ExecutingStorageJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecutingStorageJobs,
                    request_deserializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.ExecutingStorageJobsRequest.FromString,
                    response_serializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.ExecutingStorageJobsResponse.SerializeToString,
            ),
            'LatestFinalStorageJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.LatestFinalStorageJobs,
                    request_deserializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.LatestFinalStorageJobsRequest.FromString,
                    response_serializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.LatestFinalStorageJobsResponse.SerializeToString,
            ),
            'LatestSuccessfulStorageJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.LatestSuccessfulStorageJobs,
                    request_deserializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.LatestSuccessfulStorageJobsRequest.FromString,
                    response_serializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.LatestSuccessfulStorageJobsResponse.SerializeToString,
            ),
            'StorageJobsSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.StorageJobsSummary,
                    request_deserializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.StorageJobsSummaryRequest.FromString,
                    response_serializer=proto_dot_admin_dot_v1_dot_powergate__admin__pb2.StorageJobsSummaryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.admin.v1.PowergateAdminService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PowergateAdminService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def NewAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.admin.v1.PowergateAdminService/NewAddress',
            proto_dot_admin_dot_v1_dot_powergate__admin__pb2.NewAddressRequest.SerializeToString,
            proto_dot_admin_dot_v1_dot_powergate__admin__pb2.NewAddressResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Addresses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.admin.v1.PowergateAdminService/Addresses',
            proto_dot_admin_dot_v1_dot_powergate__admin__pb2.AddressesRequest.SerializeToString,
            proto_dot_admin_dot_v1_dot_powergate__admin__pb2.AddressesResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendFil(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.admin.v1.PowergateAdminService/SendFil',
            proto_dot_admin_dot_v1_dot_powergate__admin__pb2.SendFilRequest.SerializeToString,
            proto_dot_admin_dot_v1_dot_powergate__admin__pb2.SendFilResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreateStorageProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.admin.v1.PowergateAdminService/CreateStorageProfile',
            proto_dot_admin_dot_v1_dot_powergate__admin__pb2.CreateStorageProfileRequest.SerializeToString,
            proto_dot_admin_dot_v1_dot_powergate__admin__pb2.CreateStorageProfileResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StorageProfiles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.admin.v1.PowergateAdminService/StorageProfiles',
            proto_dot_admin_dot_v1_dot_powergate__admin__pb2.StorageProfilesRequest.SerializeToString,
            proto_dot_admin_dot_v1_dot_powergate__admin__pb2.StorageProfilesResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueuedStorageJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.admin.v1.PowergateAdminService/QueuedStorageJobs',
            proto_dot_admin_dot_v1_dot_powergate__admin__pb2.QueuedStorageJobsRequest.SerializeToString,
            proto_dot_admin_dot_v1_dot_powergate__admin__pb2.QueuedStorageJobsResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExecutingStorageJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.admin.v1.PowergateAdminService/ExecutingStorageJobs',
            proto_dot_admin_dot_v1_dot_powergate__admin__pb2.ExecutingStorageJobsRequest.SerializeToString,
            proto_dot_admin_dot_v1_dot_powergate__admin__pb2.ExecutingStorageJobsResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LatestFinalStorageJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.admin.v1.PowergateAdminService/LatestFinalStorageJobs',
            proto_dot_admin_dot_v1_dot_powergate__admin__pb2.LatestFinalStorageJobsRequest.SerializeToString,
            proto_dot_admin_dot_v1_dot_powergate__admin__pb2.LatestFinalStorageJobsResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LatestSuccessfulStorageJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.admin.v1.PowergateAdminService/LatestSuccessfulStorageJobs',
            proto_dot_admin_dot_v1_dot_powergate__admin__pb2.LatestSuccessfulStorageJobsRequest.SerializeToString,
            proto_dot_admin_dot_v1_dot_powergate__admin__pb2.LatestSuccessfulStorageJobsResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StorageJobsSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.admin.v1.PowergateAdminService/StorageJobsSummary',
            proto_dot_admin_dot_v1_dot_powergate__admin__pb2.StorageJobsSummaryRequest.SerializeToString,
            proto_dot_admin_dot_v1_dot_powergate__admin__pb2.StorageJobsSummaryResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
