# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto.powergate.v1 import powergate_pb2 as proto_dot_powergate_dot_v1_dot_powergate__pb2


class PowergateServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BuildInfo = channel.unary_unary(
                '/proto.powergate.v1.PowergateService/BuildInfo',
                request_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.BuildInfoRequest.SerializeToString,
                response_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.BuildInfoResponse.FromString,
                )
        self.StorageProfileIdentifier = channel.unary_unary(
                '/proto.powergate.v1.PowergateService/StorageProfileIdentifier',
                request_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.StorageProfileIdentifierRequest.SerializeToString,
                response_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.StorageProfileIdentifierResponse.FromString,
                )
        self.DefaultStorageConfig = channel.unary_unary(
                '/proto.powergate.v1.PowergateService/DefaultStorageConfig',
                request_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.DefaultStorageConfigRequest.SerializeToString,
                response_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.DefaultStorageConfigResponse.FromString,
                )
        self.SetDefaultStorageConfig = channel.unary_unary(
                '/proto.powergate.v1.PowergateService/SetDefaultStorageConfig',
                request_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.SetDefaultStorageConfigRequest.SerializeToString,
                response_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.SetDefaultStorageConfigResponse.FromString,
                )
        self.ApplyStorageConfig = channel.unary_unary(
                '/proto.powergate.v1.PowergateService/ApplyStorageConfig',
                request_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.ApplyStorageConfigRequest.SerializeToString,
                response_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.ApplyStorageConfigResponse.FromString,
                )
        self.Remove = channel.unary_unary(
                '/proto.powergate.v1.PowergateService/Remove',
                request_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.RemoveRequest.SerializeToString,
                response_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.RemoveResponse.FromString,
                )
        self.Stage = channel.stream_unary(
                '/proto.powergate.v1.PowergateService/Stage',
                request_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.StageRequest.SerializeToString,
                response_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.StageResponse.FromString,
                )
        self.ReplaceData = channel.unary_unary(
                '/proto.powergate.v1.PowergateService/ReplaceData',
                request_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.ReplaceDataRequest.SerializeToString,
                response_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.ReplaceDataResponse.FromString,
                )
        self.Get = channel.unary_stream(
                '/proto.powergate.v1.PowergateService/Get',
                request_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.GetRequest.SerializeToString,
                response_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.GetResponse.FromString,
                )
        self.WatchLogs = channel.unary_stream(
                '/proto.powergate.v1.PowergateService/WatchLogs',
                request_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.WatchLogsRequest.SerializeToString,
                response_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.WatchLogsResponse.FromString,
                )
        self.CidInfo = channel.unary_unary(
                '/proto.powergate.v1.PowergateService/CidInfo',
                request_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.CidInfoRequest.SerializeToString,
                response_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.CidInfoResponse.FromString,
                )
        self.Balance = channel.unary_unary(
                '/proto.powergate.v1.PowergateService/Balance',
                request_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.BalanceRequest.SerializeToString,
                response_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.BalanceResponse.FromString,
                )
        self.NewAddress = channel.unary_unary(
                '/proto.powergate.v1.PowergateService/NewAddress',
                request_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.NewAddressRequest.SerializeToString,
                response_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.NewAddressResponse.FromString,
                )
        self.Addresses = channel.unary_unary(
                '/proto.powergate.v1.PowergateService/Addresses',
                request_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.AddressesRequest.SerializeToString,
                response_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.AddressesResponse.FromString,
                )
        self.SendFil = channel.unary_unary(
                '/proto.powergate.v1.PowergateService/SendFil',
                request_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.SendFilRequest.SerializeToString,
                response_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.SendFilResponse.FromString,
                )
        self.SignMessage = channel.unary_unary(
                '/proto.powergate.v1.PowergateService/SignMessage',
                request_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.SignMessageRequest.SerializeToString,
                response_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.SignMessageResponse.FromString,
                )
        self.VerifyMessage = channel.unary_unary(
                '/proto.powergate.v1.PowergateService/VerifyMessage',
                request_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.VerifyMessageRequest.SerializeToString,
                response_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.VerifyMessageResponse.FromString,
                )
        self.StorageJob = channel.unary_unary(
                '/proto.powergate.v1.PowergateService/StorageJob',
                request_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.StorageJobRequest.SerializeToString,
                response_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.StorageJobResponse.FromString,
                )
        self.StorageConfigForJob = channel.unary_unary(
                '/proto.powergate.v1.PowergateService/StorageConfigForJob',
                request_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.StorageConfigForJobRequest.SerializeToString,
                response_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.StorageConfigForJobResponse.FromString,
                )
        self.QueuedStorageJobs = channel.unary_unary(
                '/proto.powergate.v1.PowergateService/QueuedStorageJobs',
                request_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.QueuedStorageJobsRequest.SerializeToString,
                response_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.QueuedStorageJobsResponse.FromString,
                )
        self.ExecutingStorageJobs = channel.unary_unary(
                '/proto.powergate.v1.PowergateService/ExecutingStorageJobs',
                request_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.ExecutingStorageJobsRequest.SerializeToString,
                response_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.ExecutingStorageJobsResponse.FromString,
                )
        self.LatestFinalStorageJobs = channel.unary_unary(
                '/proto.powergate.v1.PowergateService/LatestFinalStorageJobs',
                request_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.LatestFinalStorageJobsRequest.SerializeToString,
                response_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.LatestFinalStorageJobsResponse.FromString,
                )
        self.LatestSuccessfulStorageJobs = channel.unary_unary(
                '/proto.powergate.v1.PowergateService/LatestSuccessfulStorageJobs',
                request_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.LatestSuccessfulStorageJobsRequest.SerializeToString,
                response_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.LatestSuccessfulStorageJobsResponse.FromString,
                )
        self.StorageJobsSummary = channel.unary_unary(
                '/proto.powergate.v1.PowergateService/StorageJobsSummary',
                request_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.StorageJobsSummaryRequest.SerializeToString,
                response_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.StorageJobsSummaryResponse.FromString,
                )
        self.WatchStorageJobs = channel.unary_stream(
                '/proto.powergate.v1.PowergateService/WatchStorageJobs',
                request_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.WatchStorageJobsRequest.SerializeToString,
                response_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.WatchStorageJobsResponse.FromString,
                )
        self.CancelStorageJob = channel.unary_unary(
                '/proto.powergate.v1.PowergateService/CancelStorageJob',
                request_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.CancelStorageJobRequest.SerializeToString,
                response_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.CancelStorageJobResponse.FromString,
                )
        self.StorageDealRecords = channel.unary_unary(
                '/proto.powergate.v1.PowergateService/StorageDealRecords',
                request_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.StorageDealRecordsRequest.SerializeToString,
                response_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.StorageDealRecordsResponse.FromString,
                )
        self.RetrievalDealRecords = channel.unary_unary(
                '/proto.powergate.v1.PowergateService/RetrievalDealRecords',
                request_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.RetrievalDealRecordsRequest.SerializeToString,
                response_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.RetrievalDealRecordsResponse.FromString,
                )


class PowergateServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def BuildInfo(self, request, context):
        """Top level
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StorageProfileIdentifier(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DefaultStorageConfig(self, request, context):
        """Storage config
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDefaultStorageConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyStorageConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Remove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stage(self, request_iterator, context):
        """Data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplaceData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CidInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Balance(self, request, context):
        """Wallet
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NewAddress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Addresses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendFil(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SignMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StorageJob(self, request, context):
        """Storage Jobs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StorageConfigForJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueuedStorageJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecutingStorageJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LatestFinalStorageJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LatestSuccessfulStorageJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StorageJobsSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchStorageJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelStorageJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StorageDealRecords(self, request, context):
        """Deals
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrievalDealRecords(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PowergateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BuildInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.BuildInfo,
                    request_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.BuildInfoRequest.FromString,
                    response_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.BuildInfoResponse.SerializeToString,
            ),
            'StorageProfileIdentifier': grpc.unary_unary_rpc_method_handler(
                    servicer.StorageProfileIdentifier,
                    request_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.StorageProfileIdentifierRequest.FromString,
                    response_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.StorageProfileIdentifierResponse.SerializeToString,
            ),
            'DefaultStorageConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.DefaultStorageConfig,
                    request_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.DefaultStorageConfigRequest.FromString,
                    response_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.DefaultStorageConfigResponse.SerializeToString,
            ),
            'SetDefaultStorageConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDefaultStorageConfig,
                    request_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.SetDefaultStorageConfigRequest.FromString,
                    response_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.SetDefaultStorageConfigResponse.SerializeToString,
            ),
            'ApplyStorageConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyStorageConfig,
                    request_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.ApplyStorageConfigRequest.FromString,
                    response_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.ApplyStorageConfigResponse.SerializeToString,
            ),
            'Remove': grpc.unary_unary_rpc_method_handler(
                    servicer.Remove,
                    request_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.RemoveRequest.FromString,
                    response_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.RemoveResponse.SerializeToString,
            ),
            'Stage': grpc.stream_unary_rpc_method_handler(
                    servicer.Stage,
                    request_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.StageRequest.FromString,
                    response_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.StageResponse.SerializeToString,
            ),
            'ReplaceData': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplaceData,
                    request_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.ReplaceDataRequest.FromString,
                    response_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.ReplaceDataResponse.SerializeToString,
            ),
            'Get': grpc.unary_stream_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.GetRequest.FromString,
                    response_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.GetResponse.SerializeToString,
            ),
            'WatchLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchLogs,
                    request_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.WatchLogsRequest.FromString,
                    response_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.WatchLogsResponse.SerializeToString,
            ),
            'CidInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.CidInfo,
                    request_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.CidInfoRequest.FromString,
                    response_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.CidInfoResponse.SerializeToString,
            ),
            'Balance': grpc.unary_unary_rpc_method_handler(
                    servicer.Balance,
                    request_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.BalanceRequest.FromString,
                    response_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.BalanceResponse.SerializeToString,
            ),
            'NewAddress': grpc.unary_unary_rpc_method_handler(
                    servicer.NewAddress,
                    request_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.NewAddressRequest.FromString,
                    response_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.NewAddressResponse.SerializeToString,
            ),
            'Addresses': grpc.unary_unary_rpc_method_handler(
                    servicer.Addresses,
                    request_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.AddressesRequest.FromString,
                    response_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.AddressesResponse.SerializeToString,
            ),
            'SendFil': grpc.unary_unary_rpc_method_handler(
                    servicer.SendFil,
                    request_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.SendFilRequest.FromString,
                    response_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.SendFilResponse.SerializeToString,
            ),
            'SignMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SignMessage,
                    request_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.SignMessageRequest.FromString,
                    response_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.SignMessageResponse.SerializeToString,
            ),
            'VerifyMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyMessage,
                    request_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.VerifyMessageRequest.FromString,
                    response_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.VerifyMessageResponse.SerializeToString,
            ),
            'StorageJob': grpc.unary_unary_rpc_method_handler(
                    servicer.StorageJob,
                    request_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.StorageJobRequest.FromString,
                    response_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.StorageJobResponse.SerializeToString,
            ),
            'StorageConfigForJob': grpc.unary_unary_rpc_method_handler(
                    servicer.StorageConfigForJob,
                    request_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.StorageConfigForJobRequest.FromString,
                    response_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.StorageConfigForJobResponse.SerializeToString,
            ),
            'QueuedStorageJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.QueuedStorageJobs,
                    request_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.QueuedStorageJobsRequest.FromString,
                    response_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.QueuedStorageJobsResponse.SerializeToString,
            ),
            'ExecutingStorageJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecutingStorageJobs,
                    request_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.ExecutingStorageJobsRequest.FromString,
                    response_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.ExecutingStorageJobsResponse.SerializeToString,
            ),
            'LatestFinalStorageJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.LatestFinalStorageJobs,
                    request_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.LatestFinalStorageJobsRequest.FromString,
                    response_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.LatestFinalStorageJobsResponse.SerializeToString,
            ),
            'LatestSuccessfulStorageJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.LatestSuccessfulStorageJobs,
                    request_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.LatestSuccessfulStorageJobsRequest.FromString,
                    response_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.LatestSuccessfulStorageJobsResponse.SerializeToString,
            ),
            'StorageJobsSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.StorageJobsSummary,
                    request_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.StorageJobsSummaryRequest.FromString,
                    response_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.StorageJobsSummaryResponse.SerializeToString,
            ),
            'WatchStorageJobs': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchStorageJobs,
                    request_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.WatchStorageJobsRequest.FromString,
                    response_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.WatchStorageJobsResponse.SerializeToString,
            ),
            'CancelStorageJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelStorageJob,
                    request_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.CancelStorageJobRequest.FromString,
                    response_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.CancelStorageJobResponse.SerializeToString,
            ),
            'StorageDealRecords': grpc.unary_unary_rpc_method_handler(
                    servicer.StorageDealRecords,
                    request_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.StorageDealRecordsRequest.FromString,
                    response_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.StorageDealRecordsResponse.SerializeToString,
            ),
            'RetrievalDealRecords': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrievalDealRecords,
                    request_deserializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.RetrievalDealRecordsRequest.FromString,
                    response_serializer=proto_dot_powergate_dot_v1_dot_powergate__pb2.RetrievalDealRecordsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.powergate.v1.PowergateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PowergateService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def BuildInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.powergate.v1.PowergateService/BuildInfo',
            proto_dot_powergate_dot_v1_dot_powergate__pb2.BuildInfoRequest.SerializeToString,
            proto_dot_powergate_dot_v1_dot_powergate__pb2.BuildInfoResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StorageProfileIdentifier(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.powergate.v1.PowergateService/StorageProfileIdentifier',
            proto_dot_powergate_dot_v1_dot_powergate__pb2.StorageProfileIdentifierRequest.SerializeToString,
            proto_dot_powergate_dot_v1_dot_powergate__pb2.StorageProfileIdentifierResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DefaultStorageConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.powergate.v1.PowergateService/DefaultStorageConfig',
            proto_dot_powergate_dot_v1_dot_powergate__pb2.DefaultStorageConfigRequest.SerializeToString,
            proto_dot_powergate_dot_v1_dot_powergate__pb2.DefaultStorageConfigResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetDefaultStorageConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.powergate.v1.PowergateService/SetDefaultStorageConfig',
            proto_dot_powergate_dot_v1_dot_powergate__pb2.SetDefaultStorageConfigRequest.SerializeToString,
            proto_dot_powergate_dot_v1_dot_powergate__pb2.SetDefaultStorageConfigResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ApplyStorageConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.powergate.v1.PowergateService/ApplyStorageConfig',
            proto_dot_powergate_dot_v1_dot_powergate__pb2.ApplyStorageConfigRequest.SerializeToString,
            proto_dot_powergate_dot_v1_dot_powergate__pb2.ApplyStorageConfigResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Remove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.powergate.v1.PowergateService/Remove',
            proto_dot_powergate_dot_v1_dot_powergate__pb2.RemoveRequest.SerializeToString,
            proto_dot_powergate_dot_v1_dot_powergate__pb2.RemoveResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Stage(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/proto.powergate.v1.PowergateService/Stage',
            proto_dot_powergate_dot_v1_dot_powergate__pb2.StageRequest.SerializeToString,
            proto_dot_powergate_dot_v1_dot_powergate__pb2.StageResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReplaceData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.powergate.v1.PowergateService/ReplaceData',
            proto_dot_powergate_dot_v1_dot_powergate__pb2.ReplaceDataRequest.SerializeToString,
            proto_dot_powergate_dot_v1_dot_powergate__pb2.ReplaceDataResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/proto.powergate.v1.PowergateService/Get',
            proto_dot_powergate_dot_v1_dot_powergate__pb2.GetRequest.SerializeToString,
            proto_dot_powergate_dot_v1_dot_powergate__pb2.GetResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WatchLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/proto.powergate.v1.PowergateService/WatchLogs',
            proto_dot_powergate_dot_v1_dot_powergate__pb2.WatchLogsRequest.SerializeToString,
            proto_dot_powergate_dot_v1_dot_powergate__pb2.WatchLogsResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CidInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.powergate.v1.PowergateService/CidInfo',
            proto_dot_powergate_dot_v1_dot_powergate__pb2.CidInfoRequest.SerializeToString,
            proto_dot_powergate_dot_v1_dot_powergate__pb2.CidInfoResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Balance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.powergate.v1.PowergateService/Balance',
            proto_dot_powergate_dot_v1_dot_powergate__pb2.BalanceRequest.SerializeToString,
            proto_dot_powergate_dot_v1_dot_powergate__pb2.BalanceResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NewAddress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.powergate.v1.PowergateService/NewAddress',
            proto_dot_powergate_dot_v1_dot_powergate__pb2.NewAddressRequest.SerializeToString,
            proto_dot_powergate_dot_v1_dot_powergate__pb2.NewAddressResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Addresses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.powergate.v1.PowergateService/Addresses',
            proto_dot_powergate_dot_v1_dot_powergate__pb2.AddressesRequest.SerializeToString,
            proto_dot_powergate_dot_v1_dot_powergate__pb2.AddressesResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendFil(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.powergate.v1.PowergateService/SendFil',
            proto_dot_powergate_dot_v1_dot_powergate__pb2.SendFilRequest.SerializeToString,
            proto_dot_powergate_dot_v1_dot_powergate__pb2.SendFilResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SignMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.powergate.v1.PowergateService/SignMessage',
            proto_dot_powergate_dot_v1_dot_powergate__pb2.SignMessageRequest.SerializeToString,
            proto_dot_powergate_dot_v1_dot_powergate__pb2.SignMessageResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def VerifyMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.powergate.v1.PowergateService/VerifyMessage',
            proto_dot_powergate_dot_v1_dot_powergate__pb2.VerifyMessageRequest.SerializeToString,
            proto_dot_powergate_dot_v1_dot_powergate__pb2.VerifyMessageResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StorageJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.powergate.v1.PowergateService/StorageJob',
            proto_dot_powergate_dot_v1_dot_powergate__pb2.StorageJobRequest.SerializeToString,
            proto_dot_powergate_dot_v1_dot_powergate__pb2.StorageJobResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StorageConfigForJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.powergate.v1.PowergateService/StorageConfigForJob',
            proto_dot_powergate_dot_v1_dot_powergate__pb2.StorageConfigForJobRequest.SerializeToString,
            proto_dot_powergate_dot_v1_dot_powergate__pb2.StorageConfigForJobResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def QueuedStorageJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.powergate.v1.PowergateService/QueuedStorageJobs',
            proto_dot_powergate_dot_v1_dot_powergate__pb2.QueuedStorageJobsRequest.SerializeToString,
            proto_dot_powergate_dot_v1_dot_powergate__pb2.QueuedStorageJobsResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExecutingStorageJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.powergate.v1.PowergateService/ExecutingStorageJobs',
            proto_dot_powergate_dot_v1_dot_powergate__pb2.ExecutingStorageJobsRequest.SerializeToString,
            proto_dot_powergate_dot_v1_dot_powergate__pb2.ExecutingStorageJobsResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LatestFinalStorageJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.powergate.v1.PowergateService/LatestFinalStorageJobs',
            proto_dot_powergate_dot_v1_dot_powergate__pb2.LatestFinalStorageJobsRequest.SerializeToString,
            proto_dot_powergate_dot_v1_dot_powergate__pb2.LatestFinalStorageJobsResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LatestSuccessfulStorageJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.powergate.v1.PowergateService/LatestSuccessfulStorageJobs',
            proto_dot_powergate_dot_v1_dot_powergate__pb2.LatestSuccessfulStorageJobsRequest.SerializeToString,
            proto_dot_powergate_dot_v1_dot_powergate__pb2.LatestSuccessfulStorageJobsResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StorageJobsSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.powergate.v1.PowergateService/StorageJobsSummary',
            proto_dot_powergate_dot_v1_dot_powergate__pb2.StorageJobsSummaryRequest.SerializeToString,
            proto_dot_powergate_dot_v1_dot_powergate__pb2.StorageJobsSummaryResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def WatchStorageJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/proto.powergate.v1.PowergateService/WatchStorageJobs',
            proto_dot_powergate_dot_v1_dot_powergate__pb2.WatchStorageJobsRequest.SerializeToString,
            proto_dot_powergate_dot_v1_dot_powergate__pb2.WatchStorageJobsResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CancelStorageJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.powergate.v1.PowergateService/CancelStorageJob',
            proto_dot_powergate_dot_v1_dot_powergate__pb2.CancelStorageJobRequest.SerializeToString,
            proto_dot_powergate_dot_v1_dot_powergate__pb2.CancelStorageJobResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StorageDealRecords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.powergate.v1.PowergateService/StorageDealRecords',
            proto_dot_powergate_dot_v1_dot_powergate__pb2.StorageDealRecordsRequest.SerializeToString,
            proto_dot_powergate_dot_v1_dot_powergate__pb2.StorageDealRecordsResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RetrievalDealRecords(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/proto.powergate.v1.PowergateService/RetrievalDealRecords',
            proto_dot_powergate_dot_v1_dot_powergate__pb2.RetrievalDealRecordsRequest.SerializeToString,
            proto_dot_powergate_dot_v1_dot_powergate__pb2.RetrievalDealRecordsResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
